### ISSUE TITLE
Update the hover style for top-menu buttons

### ISSUE THREAD

**Issue by piopon** [piopon/smart-words#14]
Current on-hover style for top-menu items is not looking good:
![image](https://user-images.githubusercontent.com/22420752/186020913-b563b53f-7abb-45cc-a9e6-daa9a4303234.png)
We should update it and maybe just add some shadow or other image effect

**Comment by developer-irfan** [comment]
Hey @piopon this hover style is not looking good, i can add better hover effect.

**Comment by piopon** [comment]
Hi. I've added cotribution guidelines to the repository so feel free to take this issue.
I don't know if you can assign yourself to this issue but if not then give me a shout and I'll do it for you.
When it comes to the final effect I was thinking of some kind of shadow or outline to the icon.
